repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: local
  hooks:
    - id: lua-format
      name: format lua files
      language: lua
      entry: "lua-format"
      files: \.lua$
      exclude: nvim/plugin/packer_compiled.lua
      pass_filenames: true
