#!/bin/sh

xsetroot -cursor_name left_ptr
/usr/bin/sxhkd -c ~/.config/sxhkd/sxhkdrc &
polybar bottom --config=~/.config/polybar/polybar.ini &
# polybar top --config=~/.config/polybar/polybar.ini &
picom -b
feh --bg-scale ~/anime/green-brown-yellow.jpg

bspc config border_width	1
bspc config window_gap		3

bspc config split_ratio		0.5
bspc config focus_follows_pointer	false
bspc config pointer_modifier	mod1

bspc config automatic_scheme	spiral
