require("plugins.set")
require("plugins.packer")
require("plugins.remap")
require("plugins.lualine")
require("plugins.lsp")
require("plugins.completion")
require("plugins.telescope")
require("plugins.dap")
require("plugins.comment")
require("plugins." .. vim.g['global_colorscheme'])
require('plugins.impatient')
require('plugins.cursorline')
require('plugins.colorizer')
require('plugins.rest')
require('plugins.whichkey')
require('plugins.sad')
require('plugins.ssr')
-- require('plugins.nvim_tree')
