require('plugins.impatient')
require("plugins.set")
require("plugins.packer")
require("plugins.remap")
require("plugins.lualine")
require("plugins.lsp_zero")
require("plugins.lsp_signature")
-- require("plugins.lsp")
require("plugins.lint")
require("plugins.completion")
require("plugins.telescope")
require("plugins.git_worktree")
require("plugins.gitsigns")
require("plugins.dap")
require("plugins.coderunner")
require("plugins.comment")
require("plugins." .. vim.g['global_colorscheme'])
require('plugins.colorizer')
require('plugins.rest')
require('plugins.whichkey')
require('plugins.treesj')
require('plugins.winsep')
require('plugins.dressing')
require('plugins.icon_picker')
require('plugins.colortils')
require("plugins.exrc")
require("plugins.crates")
require("plugins.carbon")
-- require('plugins.nvim_tree')
