name: deploy

on:
  push:
    branches:
      - '**'

jobs:

  deploy:

    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: set git config
        shell: bash
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "<>"

      - name: touch file
        shell: bash
        run: |
          set -e
          touch test.txt

      - name: commit and push
        shell: bash
        run: |
          set -e
          git add .
          git commit -m "test"
          git push
