name: test

on:
  workflow_dispatch:
    inputs:
      my-field:
        description: 'my field'
        required: false
        default: ''

jobs:

  test:
    runs-on: [ubuntu, xsmall]
    strategy:
      matrix:
        python-version: ["3.10.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run python file
        run: python .github/workflows/test.py

      - name: Check exit code
        run: echo $EXIT_CODE
